### ISSUE TITLE
Data set can be made active when it is not on the chart

### ISSUE THREAD

**Issue by coopsatwork** [CMDT/TimeSeriesDataCapture#53]
Steps to reproduce:

Use [this view](https://timeseriesdatacapture-spwa.herokuapp.com/#!/view?runs=2B497C4DAFF48A9C!178&columns=2B497C4DAFF48A9C!178:RTH%2B2B497C4DAFF48A9C!178:DAC&viewVector=%7B%22k%22:0.79,%22x%22:228.46,%22y%22:93.98%7D&offsetVector=%7B%22x%22:0,%22y%22:0%7D&active=2B497C4DAFF48A9C!178%2BT(Cell1))

**Expected behaviour**
It should not be possible to make a dataset active, if its data is not on the screen.
1. A user cannot make a dataset active, if it is not selected (i.e. it's checkbox must be checked)
Clicking on an unchecked dataset will have no effect.

2. If the user un-checks the active dataset, then its data will not be on the screen. If it is the active dataset, the simplest thing to do is make no dataset the active dataset. Remove the axis labels, prompting the user to make the decision.

3. If the URL specifies a data set which is not on screen, then this an error.
 Inform the user that there has been an error, and to revert to a predictable state. The predictable state should be nothing on the chart, and no columns selected.
The user can then select what columns need to be displayed.

**Actual Behaviour**
The chart axes show the name and scale for the active data set, but it is not plotted. It is easy to become confused as to what data is active.

**Comment by coopsatwork** [comment]
Check for active data set when unchecking item - remove the active dataset indication if the item being unchecked is the active dataset.
Check for checked item when selecting an item - if item is checked, then make active. If unchecked, then ignore.

**Comment by YusofBandar** [comment]
Hidden columns cannot become the active trend
