### ISSUE TITLE
View Page: Annotations and Offset Line Rendering 

### ISSUE THREAD

**Issue by YusofBandar** [CMDT/TimeSeriesDataCapture#6]
**Current Behaviour**
Both the annotations and red offset line are being rendered past the graph range

**Expected Behaviour**
Annotations and red offset line only rendered within the graph range

**Reproduce Current Behaviour**
Offset the graph pass either the x or y axis

**Comment by coopsatwork** [comment]
Clipping need a bit more research - hence fix deferred

**Comment by YusofBandar** [comment]
Offset line is no longer shown past graph extents
