### ISSUE TITLE
Credentials are hardcoded in SPWA

### ISSUE THREAD

**Issue by YusofBandar** [CMDT/TimeSeriesDataCapture#70]
**Current Behaviour**
All credentials used by SPWA are hard coded

**Expected Behaviour**
Credentials should be retrieved from config file, which is generated when SPWA is served

**Comment by coopsatwork** [comment]
We create a file on server start-up, which will be served along with the SPWA.
See https://github.com/CMDT/AppatellaExerciseBuilder/blob/master/index.js for detail on how to do this.

**Comment by YusofBandar** [comment]
Hardcoded values have been removed. Details are written when deployed
