### ISSUE TITLE
 Hardcoded values for credentials in BrowseData

### ISSUE THREAD

**Issue by coopsatwork** [CMDT/TimeSeriesDataCapture#72]
This will alleviate problems requiring fixes in [AliceLiveProjects](https://github.com/aliceliveprojects/TimeSeriesDataCapture_BrowseData/commits/master):

https://github.com/aliceliveprojects/TimeSeriesDataCapture_BrowseData/commit/50ed1ebce2d0d2d19c2c2117698d18a29e3cc606  
https://github.com/aliceliveprojects/TimeSeriesDataCapture_BrowseData/commit/0943822bf3643e410da2897e1653d9437aee8e14

**Comment by YusofBandar** [comment]
All hardcoded details are now removed. Env vars are used to configure browse data.
