### ISSUE TITLE
Documentation needed for adding OneDrive developer account details

### ISSUE THREAD

**Issue by coopsatwork** [CMDT/TimeSeriesDataCapture#73]
We need to ensure the user knows how to associate a OneDrive developer account correctly, and register for an app id, during deployment

Also need to underline that the account MUST be a student or staff MS Office 365 account, rather than a straight consumer Outlook account.

**Comment by YusofBandar** [comment]
Documentation updated, see https://github.com/CMDT/TimeSeriesDataCapture#onedrive-application-setup
